package onlineworldpay

const (
	// HTTPOK Status OK=200
	HTTPOK = 200
	// HTTPREQERR Request Error = 400
	HTTPREQERR = 400
	// HTTPAUTHERR Auth Error = 401
	HTTPAUTHERR = 401
	// HTTPNOTFOUND Not Found = 404
	HTTPNOTFOUND = 404
	// HTTPMETHODUNSUPPORT Unsupported Method = 405
	HTTPMETHODUNSUPPORT = 405
	// HTTPMEDIAUNSUPPORT Unsupported Media = 415
	HTTPMEDIAUNSUPPORT = 415
	// HTTPSERVERERROR Server Error = 500
	HTTPSERVERERROR = 500
)
