package fsm

const (

	/* STATES */

	// Device
	DEV_NOT_READY State = "DEVICE_NOT_READY"
	DEV_READY State = "DEVICE_READY"

	// Consumer
	CON_DISCOVER_DEV State = "CONSUMER_DISCOVER_DEVICES"
	CON_DEV_AVAILABLE State = "CONSUMER_DEVICES_AVAILABLE"
	CON_READY State = "CONSUMER_READY"
	CON_REQ_SVC State = "CONSUMER_REQUEST_SERVICES"
	CON_SVC_AVAILABLE State = "CONSUMER_SERVICES_AVAILABLE"
	CON_SEL_SVC State = "CONSUMER_SELECT_SERVICE"
	CON_AWAIT_PAYMENT State = "CONSUMER_AWAIT_PAYMENT"
	CON_PROC_PAYMENT State = "CONSUMER_PROCESS_PAYMENT"
	CON_PAYMENT_ACCEPTED State = "CONSUMER_PAYMENT_ACCEPTED"
	CON_DELIVERING_SERVICE State = "CONSUMER_DELIVERYING_SERVICE"

	// Producer
	PRO_READY State = "PRODUCER_READY"
	PRO_BROADCAST State = "PRODUCER_BROADCAST"

	/* INPUTS */

//	INIT_DEV = "INIT_DEVICE"
//	START_DISC_DEV = "START_DISCOVER_DEVICE"
//	DEV_NOT_FOUND = "DEVICE_NOT_FOUND"
//	START_DISC_SVC = "START_DISCOVER_SERVICE"
//	DEV_FOUND = "DEVICES_FOUND"
//	INIT_CONSUMER = "INIT_CONSUMER"
//	RESET_CONSUMER = "RESET_CONSUMER"
//	REQ_SVC = "REQUEST_SERVICES"
//	NO_SVC_FOUND = "NO_SERVICES_FOUND"
//	SVC_FOUND = "SERVICES_FOUND"
//	END_SVC_DELIVERY = "END_SERVICE_DELIVERY"
//	SEL_SVC = "SELECT_SERVICE"
//	SVC_SELECTED = "SERVICE_SELECTED"
//	SVC_SELECT_ERR = "SERVICE_SELECTION_ERROR"
//	PAY_ERR = "PAYMENT_ERROR"
//	PAY_SUCCESS = "PAYMENT_SUCCESS"
//	BEGIN_SVC_DELIVERY = "BEGIN_SERVICE_DELIVERY"
//	ADD_SVC = "ADD_SERVICE"
//	REM_SVC = "REMOVE_SERVICE"
//	INIT_PROD = "INIT_PRODUCER"
//	START_SVC_BCAST = "START_SERVICE_BROADCAST"
//	STOP_SVC_BCAST = "STOP_SERVICE_BROADCAST"

	/* Contexts */

	CTX_INIT_DEVICE Input = "CTX_INIT_DEVICE"
)